// 描画に関する定数を定義
export const DRAWING_CONSTANTS = {
  // タイル関連
  TILE_BORDER_COLOR: '#666',
  TILE_BORDER_WIDTH: 1,
  
  // 選択状態
  SELECTED_BORDER_COLOR: '#FFD700',
  SELECTED_BORDER_WIDTH: 3,
  
  // ドラッグ範囲
  DRAG_ALPHA: 0.7,
  DRAG_COLOR: '#FFD700',
  DRAG_STROKE_COLOR: '#FFA500',
  DRAG_STROKE_WIDTH: 2,
  
  // 効果範囲
  EFFECT_ALPHA: 0.4,
  DEFAULT_EFFECT_COLOR: '#90EE90',
  PARK_EFFECT_COLOR: '#90EE90',
  POLICE_EFFECT_COLOR: '#FF00FF', // 派手な蛍光ピンク
  
  // デフォルト色
  DEFAULT_TILE_COLOR: '#9CA3AF'
} as const;
